{% set version = '1.11.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fakemake
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fakemake_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fakemake/fakemake_{{ version }}.tar.gz
  sha256: 8762f3d321f9d06dfafad2ea4fb56c6fa5dea2a37d3a756efea4d43bbed96afa

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-makefiler
    - r-fritools
    - r-igraph
  run:
    - r-base
    - r-makefiler
    - r-fritools
    - r-igraph

test:
  commands:
    - $R -e "library('fakemake')"           # [not win]
    - "\"%R%\" -e \"library('fakemake')\""  # [win]

about:
  home: https://gitlab.com/fvafrcu/fakemake
  license: BSD-2-Clause
  summary: Use R as a minimal build system. This might come in handy if you are developing R
    packages and can not use a proper build system. Stay away if you can (use a proper
    build system).
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: fakemake
# Title: Mock the Unix Make Utility
# Version: 1.11.1
# Authors@R: person(given = "Andreas Dominik", family = "Cullmann", role = c("aut", "cre"), email = "fvafrcu@mailbox.org")
# Description: Use R as a minimal build system. This might come in handy if you are developing R packages and can not use a proper build system. Stay away if you can (use a proper build system).
# License: BSD_2_clause + file LICENSE
# URL: https://gitlab.com/fvafrcu/fakemake
# Depends: R (>= 3.3.0)
# Imports: graphics, fritools, igraph, MakefileR, utils
# Suggests: cleanr, covr, cyclocomp, devtools, hunspell, knitr, lintr, pkgbuild, pkgload, rasciidoc, rmarkdown, roxygen2, rprojroot, RUnit, spelling, testthat, withr, usethis
# VignetteBuilder: knitr, rasciidoc
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-08-15 21:48:05 UTC; qwer
# Author: Andreas Dominik Cullmann [aut, cre]
# Maintainer: Andreas Dominik Cullmann <fvafrcu@mailbox.org>
# Repository: CRAN
# Date/Publication: 2023-08-15 22:10:01 UTC
